---
name: "Rust Build"
"on":
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  rust_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions/checkout@v5
      - name: Install rust stable
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Build Debug
        run: cargo build --release
      - name: Build Release
        run: cargo build --verbose --release
